version: "3"
services:
  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
        - "postgres_datadir:/var/lib/postgresql/data"
    ports:
      - "65466:5432"
    expose:
      - "5432"

  nbxplorer:
    image: nicolasdorier/nbxplorer:2.1.47
    restart: unless-stopped
    ports:
      - "65467:65467"
    expose:
      - "65467"
    env_file:
      - .env
    environment:
      NBXPLORER_NETWORK: ${NETWORK:-regtest}
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://bitcoind:65468/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:65469
      NBXPLORER_BTCRPCUSER: ceiwHEbqWI83
      NBXPLORER_BTCRPCPASSWORD: DwubwWsoo3
      NBXPLORER_BIND: 0.0.0.0:65467
      NBXPLORER_MINGAPSIZE: 5
      NBXPLORER_MAXGAPSIZE: 10
      NBXPLORER_VERBOSE: 1
      NBXPLORER_NOAUTH: 1
    volumes:
      - "nbxplorer_datadir:/datadir"
    links:
      - bitcoind

  bitcoind:
    restart: unless-stopped
    image: btcpayserver/bitcoin:0.20.1
    env_file:
      - .env
    environment:
      BITCOIN_NETWORK: ${NETWORK:-regtest}
      BITCOIN_EXTRA_ARGS: |-
        rpcuser=ceiwHEbqWI83
        rpcpassword=DwubwWsoo3
        rpcport=65468
        rpcbind=0.0.0.0:65468
        port=65469
        whitelist=0.0.0.0/0
        zmqpubrawblock=tcp://0.0.0.0:65436
        zmqpubrawtx=tcp://0.0.0.0:65437
        deprecatedrpc=signrawtransaction
        fallbackfee=0.0002
    ports:
      - "65468:65468"
      - "65469:65469"
    expose:
      - "65468" # RPC
      - "65469" # P2P
      - "65436" # ZMQ
      - "65437" # ZMQ
    volumes:
      - "bitcoin_datadir:/data"

volumes:
  postgres_datadir:
  bitcoin_datadir:
  nbxplorer_datadir:  